namespace ProxiFyreUI.Forms
{
    partial class MainForm
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.Panel headerPanel;
        private System.Windows.Forms.Label titleLabel;
        private System.Windows.Forms.Label serviceStateLabel;
        private System.Windows.Forms.Label serviceStateValueLabel;
        private System.Windows.Forms.Label configurationStateLabel;
        private System.Windows.Forms.Label configurationStateValueLabel;
        private System.Windows.Forms.Label changesStateLabel;
        private System.Windows.Forms.Label changesStateValueLabel;
        private System.Windows.Forms.Button startServiceButton;
        private System.Windows.Forms.Button stopServiceButton;
        private System.Windows.Forms.Button restartServiceButton;
        private System.Windows.Forms.Button installServiceButton;
        private System.Windows.Forms.Button headerUninstallServiceButton;
        private System.Windows.Forms.TabControl mainTabControl;
        private System.Windows.Forms.TabPage routingTabPage;
        private System.Windows.Forms.Panel routingButtonsPanel;
        private System.Windows.Forms.Button addRuleButton;
        private System.Windows.Forms.Button editRuleButton;
        private System.Windows.Forms.Button duplicateRuleButton;
        private System.Windows.Forms.Button removeRuleButton;
        private System.Windows.Forms.Button moveUpRuleButton;
        private System.Windows.Forms.Button moveDownRuleButton;
        private System.Windows.Forms.DataGridView routingGrid;
        private System.Windows.Forms.DataGridViewTextBoxColumn orderColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn applicationsColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn endpointColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn authenticationColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn transportColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn protocolsColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn addressFamiliesColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn warningsColumn;
        private System.Windows.Forms.TabPage exclusionsTabPage;
        private System.Windows.Forms.Label exclusionsExplanationLabel;
        private System.Windows.Forms.FlowLayoutPanel exclusionsButtonsPanel;
        private System.Windows.Forms.Button addRunningExclusionButton;
        private System.Windows.Forms.Button addExecutableExclusionButton;
        private System.Windows.Forms.Button addPathExclusionButton;
        private System.Windows.Forms.Button addManualExclusionButton;
        private System.Windows.Forms.Button removeExclusionButton;
        private System.Windows.Forms.ListBox exclusionsListBox;
        private System.Windows.Forms.TabPage logsTabPage;
        private System.Windows.Forms.FlowLayoutPanel logsToolbarPanel;
        private System.Windows.Forms.CheckBox followLogsCheckBox;
        private System.Windows.Forms.Label logLevelFilterLabel;
        private System.Windows.Forms.ComboBox logLevelFilterComboBox;
        private System.Windows.Forms.Label logSearchLabel;
        private System.Windows.Forms.TextBox logSearchTextBox;
        private System.Windows.Forms.Button copySelectedLogButton;
        private System.Windows.Forms.Button copyVisibleLogButton;
        private System.Windows.Forms.Button clearLogViewButton;
        private System.Windows.Forms.Button openLogFileButton;
        private System.Windows.Forms.Button openLogsButton;
        private System.Windows.Forms.Button reloadLogsButton;
        private System.Windows.Forms.RichTextBox logRichTextBox;
        private System.Windows.Forms.Label logStatusLabel;
        private System.Windows.Forms.TabPage settingsTabPage;
        private System.Windows.Forms.GroupBox engineSettingsGroupBox;
        private System.Windows.Forms.Label enginePathLabel;
        private System.Windows.Forms.TextBox enginePathTextBox;
        private System.Windows.Forms.Label configurationPathLabel;
        private System.Windows.Forms.TextBox configurationPathTextBox;
        private System.Windows.Forms.Label logPathLabel;
        private System.Windows.Forms.TextBox logPathTextBox;
        private System.Windows.Forms.Button browseEngineButton;
        private System.Windows.Forms.Button openConfigurationFolderButton;
        private System.Windows.Forms.Button openLogFolderButton;
        private System.Windows.Forms.GroupBox configurationSettingsGroupBox;
        private System.Windows.Forms.Label logLevelLabel;
        private System.Windows.Forms.Label logLevelRestartNoteLabel;
        private System.Windows.Forms.ComboBox logLevelComboBox;
        private System.Windows.Forms.CheckBox bypassLanCheckBox;
        private System.Windows.Forms.Label bypassLanExplanationLabel;
        private System.Windows.Forms.CheckBox minimizeToTrayCheckBox;
        private System.Windows.Forms.GroupBox diagnosticsGroupBox;
        private System.Windows.Forms.Label serviceNameLabel;
        private System.Windows.Forms.Label serviceNameValueLabel;
        private System.Windows.Forms.Label guiVersionLabel;
        private System.Windows.Forms.Label guiVersionValueLabel;
        private System.Windows.Forms.Label engineVersionLabel;
        private System.Windows.Forms.Label engineVersionValueLabel;
        private System.Windows.Forms.Label architectureLabel;
        private System.Windows.Forms.Label architectureValueLabel;
        private System.Windows.Forms.Button copyDiagnosticsButton;
        private System.Windows.Forms.Button uninstallServiceButton;
        private System.Windows.Forms.Label uninstallNoteLabel;
        private System.Windows.Forms.Panel actionPanel;
        private System.Windows.Forms.Button reloadButton;
        private System.Windows.Forms.Button validateButton;
        private System.Windows.Forms.Button saveButton;
        private System.Windows.Forms.Button applyRestartButton;
        private System.Windows.Forms.ProgressBar operationProgressBar;
        private System.Windows.Forms.StatusStrip statusStrip;
        private System.Windows.Forms.ToolStripStatusLabel statusStripLabel;
        private System.Windows.Forms.NotifyIcon notifyIcon;
        private System.Windows.Forms.ContextMenuStrip trayContextMenu;
        private System.Windows.Forms.ToolStripMenuItem trayOpenMenuItem;
        private System.Windows.Forms.ToolStripSeparator traySeparator1;
        private System.Windows.Forms.ToolStripMenuItem trayServiceStatusMenuItem;
        private System.Windows.Forms.ToolStripMenuItem trayStartMenuItem;
        private System.Windows.Forms.ToolStripMenuItem trayStopMenuItem;
        private System.Windows.Forms.ToolStripMenuItem trayRestartMenuItem;
        private System.Windows.Forms.ToolStripSeparator traySeparator2;
        private System.Windows.Forms.ToolStripMenuItem trayOpenLogsMenuItem;
        private System.Windows.Forms.ToolStripMenuItem trayExitMenuItem;
        private System.Windows.Forms.Timer serviceRefreshTimer;

        protected override void Dispose(bool disposing)
        {
            if (disposing) components?.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.headerPanel = new System.Windows.Forms.Panel();
            this.headerUninstallServiceButton = new System.Windows.Forms.Button();
            this.installServiceButton = new System.Windows.Forms.Button();
            this.restartServiceButton = new System.Windows.Forms.Button();
            this.stopServiceButton = new System.Windows.Forms.Button();
            this.startServiceButton = new System.Windows.Forms.Button();
            this.changesStateValueLabel = new System.Windows.Forms.Label();
            this.changesStateLabel = new System.Windows.Forms.Label();
            this.configurationStateValueLabel = new System.Windows.Forms.Label();
            this.configurationStateLabel = new System.Windows.Forms.Label();
            this.serviceStateValueLabel = new System.Windows.Forms.Label();
            this.serviceStateLabel = new System.Windows.Forms.Label();
            this.titleLabel = new System.Windows.Forms.Label();
            this.mainTabControl = new System.Windows.Forms.TabControl();
            this.routingTabPage = new System.Windows.Forms.TabPage();
            this.routingGrid = new System.Windows.Forms.DataGridView();
            this.orderColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.applicationsColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.endpointColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.authenticationColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.transportColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.protocolsColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.addressFamiliesColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.warningsColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.routingButtonsPanel = new System.Windows.Forms.Panel();
            this.moveDownRuleButton = new System.Windows.Forms.Button();
            this.moveUpRuleButton = new System.Windows.Forms.Button();
            this.removeRuleButton = new System.Windows.Forms.Button();
            this.duplicateRuleButton = new System.Windows.Forms.Button();
            this.editRuleButton = new System.Windows.Forms.Button();
            this.addRuleButton = new System.Windows.Forms.Button();
            this.exclusionsTabPage = new System.Windows.Forms.TabPage();
            this.exclusionsListBox = new System.Windows.Forms.ListBox();
            this.exclusionsButtonsPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.addRunningExclusionButton = new System.Windows.Forms.Button();
            this.addExecutableExclusionButton = new System.Windows.Forms.Button();
            this.addPathExclusionButton = new System.Windows.Forms.Button();
            this.addManualExclusionButton = new System.Windows.Forms.Button();
            this.removeExclusionButton = new System.Windows.Forms.Button();
            this.exclusionsExplanationLabel = new System.Windows.Forms.Label();
            this.logsTabPage = new System.Windows.Forms.TabPage();
            this.logRichTextBox = new System.Windows.Forms.RichTextBox();
            this.logStatusLabel = new System.Windows.Forms.Label();
            this.logsToolbarPanel = new System.Windows.Forms.FlowLayoutPanel();
            this.followLogsCheckBox = new System.Windows.Forms.CheckBox();
            this.logLevelFilterLabel = new System.Windows.Forms.Label();
            this.logLevelFilterComboBox = new System.Windows.Forms.ComboBox();
            this.logSearchLabel = new System.Windows.Forms.Label();
            this.logSearchTextBox = new System.Windows.Forms.TextBox();
            this.copySelectedLogButton = new System.Windows.Forms.Button();
            this.copyVisibleLogButton = new System.Windows.Forms.Button();
            this.clearLogViewButton = new System.Windows.Forms.Button();
            this.openLogFileButton = new System.Windows.Forms.Button();
            this.openLogsButton = new System.Windows.Forms.Button();
            this.reloadLogsButton = new System.Windows.Forms.Button();
            this.settingsTabPage = new System.Windows.Forms.TabPage();
            this.uninstallNoteLabel = new System.Windows.Forms.Label();
            this.uninstallServiceButton = new System.Windows.Forms.Button();
            this.diagnosticsGroupBox = new System.Windows.Forms.GroupBox();
            this.copyDiagnosticsButton = new System.Windows.Forms.Button();
            this.architectureValueLabel = new System.Windows.Forms.Label();
            this.architectureLabel = new System.Windows.Forms.Label();
            this.engineVersionValueLabel = new System.Windows.Forms.Label();
            this.engineVersionLabel = new System.Windows.Forms.Label();
            this.guiVersionValueLabel = new System.Windows.Forms.Label();
            this.guiVersionLabel = new System.Windows.Forms.Label();
            this.serviceNameValueLabel = new System.Windows.Forms.Label();
            this.serviceNameLabel = new System.Windows.Forms.Label();
            this.configurationSettingsGroupBox = new System.Windows.Forms.GroupBox();
            this.bypassLanExplanationLabel = new System.Windows.Forms.Label();
            this.minimizeToTrayCheckBox = new System.Windows.Forms.CheckBox();
            this.bypassLanCheckBox = new System.Windows.Forms.CheckBox();
            this.logLevelComboBox = new System.Windows.Forms.ComboBox();
            this.logLevelLabel = new System.Windows.Forms.Label();
            this.logLevelRestartNoteLabel = new System.Windows.Forms.Label();
            this.engineSettingsGroupBox = new System.Windows.Forms.GroupBox();
            this.openLogFolderButton = new System.Windows.Forms.Button();
            this.openConfigurationFolderButton = new System.Windows.Forms.Button();
            this.browseEngineButton = new System.Windows.Forms.Button();
            this.logPathTextBox = new System.Windows.Forms.TextBox();
            this.logPathLabel = new System.Windows.Forms.Label();
            this.configurationPathTextBox = new System.Windows.Forms.TextBox();
            this.configurationPathLabel = new System.Windows.Forms.Label();
            this.enginePathTextBox = new System.Windows.Forms.TextBox();
            this.enginePathLabel = new System.Windows.Forms.Label();
            this.actionPanel = new System.Windows.Forms.Panel();
            this.operationProgressBar = new System.Windows.Forms.ProgressBar();
            this.applyRestartButton = new System.Windows.Forms.Button();
            this.saveButton = new System.Windows.Forms.Button();
            this.validateButton = new System.Windows.Forms.Button();
            this.reloadButton = new System.Windows.Forms.Button();
            this.statusStrip = new System.Windows.Forms.StatusStrip();
            this.statusStripLabel = new System.Windows.Forms.ToolStripStatusLabel();
            this.trayContextMenu = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.trayOpenMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.traySeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.trayServiceStatusMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.trayStartMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.trayStopMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.trayRestartMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.traySeparator2 = new System.Windows.Forms.ToolStripSeparator();
            this.trayOpenLogsMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.trayExitMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.notifyIcon = new System.Windows.Forms.NotifyIcon(this.components);
            this.serviceRefreshTimer = new System.Windows.Forms.Timer(this.components);
            this.headerPanel.SuspendLayout();
            this.mainTabControl.SuspendLayout();
            this.routingTabPage.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.routingGrid)).BeginInit();
            this.routingButtonsPanel.SuspendLayout();
            this.exclusionsTabPage.SuspendLayout();
            this.exclusionsButtonsPanel.SuspendLayout();
            this.logsTabPage.SuspendLayout();
            this.logsToolbarPanel.SuspendLayout();
            this.settingsTabPage.SuspendLayout();
            this.diagnosticsGroupBox.SuspendLayout();
            this.configurationSettingsGroupBox.SuspendLayout();
            this.engineSettingsGroupBox.SuspendLayout();
            this.actionPanel.SuspendLayout();
            this.statusStrip.SuspendLayout();
            this.trayContextMenu.SuspendLayout();
            this.SuspendLayout();
            // headerPanel
            this.headerPanel.Controls.Add(this.headerUninstallServiceButton);
            this.headerPanel.Controls.Add(this.installServiceButton);
            this.headerPanel.Controls.Add(this.restartServiceButton);
            this.headerPanel.Controls.Add(this.stopServiceButton);
            this.headerPanel.Controls.Add(this.startServiceButton);
            this.headerPanel.Controls.Add(this.changesStateValueLabel);
            this.headerPanel.Controls.Add(this.changesStateLabel);
            this.headerPanel.Controls.Add(this.configurationStateValueLabel);
            this.headerPanel.Controls.Add(this.configurationStateLabel);
            this.headerPanel.Controls.Add(this.serviceStateValueLabel);
            this.headerPanel.Controls.Add(this.serviceStateLabel);
            this.headerPanel.Controls.Add(this.titleLabel);
            this.headerPanel.Dock = System.Windows.Forms.DockStyle.Top;
            this.headerPanel.Location = new System.Drawing.Point(0, 0);
            this.headerPanel.Name = "headerPanel";
            this.headerPanel.Padding = new System.Windows.Forms.Padding(12);
            this.headerPanel.Size = new System.Drawing.Size(1114, 102);
            this.headerPanel.TabIndex = 0;
            this.titleLabel.AutoSize = true;
            this.titleLabel.Font = global::ProxiFyreUI.Infrastructure.WinFormsFontBootstrap.CreateUiFont("Segoe UI Semibold", 16F, System.Drawing.FontStyle.Bold);
            this.titleLabel.Location = new System.Drawing.Point(12, 10);
            this.titleLabel.Name = "titleLabel";
            this.titleLabel.Size = new System.Drawing.Size(109, 30);
            this.titleLabel.TabIndex = 0;
            this.titleLabel.Text = "ProxiFyre";
            this.serviceStateLabel.AutoSize = true;
            this.serviceStateLabel.Location = new System.Drawing.Point(173, 17);
            this.serviceStateLabel.Name = "serviceStateLabel";
            this.serviceStateLabel.Size = new System.Drawing.Size(47, 15);
            this.serviceStateLabel.TabIndex = 1;
            this.serviceStateLabel.Text = "Service:";
            this.serviceStateValueLabel.AutoSize = true;
            this.serviceStateValueLabel.Font = global::ProxiFyreUI.Infrastructure.WinFormsFontBootstrap.CreateUiFont("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            this.serviceStateValueLabel.Location = new System.Drawing.Point(226, 17);
            this.serviceStateValueLabel.Name = "serviceStateValueLabel";
            this.serviceStateValueLabel.Size = new System.Drawing.Size(57, 15);
            this.serviceStateValueLabel.TabIndex = 2;
            this.serviceStateValueLabel.Text = "Unknown";
            this.configurationStateLabel.AutoSize = true;
            this.configurationStateLabel.Location = new System.Drawing.Point(350, 17);
            this.configurationStateLabel.Name = "configurationStateLabel";
            this.configurationStateLabel.Size = new System.Drawing.Size(84, 15);
            this.configurationStateLabel.TabIndex = 3;
            this.configurationStateLabel.Text = "Configuration:";
            this.configurationStateValueLabel.AutoSize = true;
            this.configurationStateValueLabel.Font = global::ProxiFyreUI.Infrastructure.WinFormsFontBootstrap.CreateUiFont("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            this.configurationStateValueLabel.Location = new System.Drawing.Point(440, 17);
            this.configurationStateValueLabel.Name = "configurationStateValueLabel";
            this.configurationStateValueLabel.Size = new System.Drawing.Size(65, 15);
            this.configurationStateValueLabel.TabIndex = 4;
            this.configurationStateValueLabel.Text = "Not loaded";
            this.changesStateLabel.AutoSize = true;
            this.changesStateLabel.Location = new System.Drawing.Point(621, 17);
            this.changesStateLabel.Name = "changesStateLabel";
            this.changesStateLabel.Size = new System.Drawing.Size(55, 15);
            this.changesStateLabel.TabIndex = 5;
            this.changesStateLabel.Text = "Changes:";
            this.changesStateValueLabel.AutoSize = true;
            this.changesStateValueLabel.Font = global::ProxiFyreUI.Infrastructure.WinFormsFontBootstrap.CreateUiFont("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            this.changesStateValueLabel.Location = new System.Drawing.Point(682, 17);
            this.changesStateValueLabel.Name = "changesStateValueLabel";
            this.changesStateValueLabel.Size = new System.Drawing.Size(57, 15);
            this.changesStateValueLabel.TabIndex = 6;
            this.changesStateValueLabel.Text = "Unknown";
            this.startServiceButton.Location = new System.Drawing.Point(15, 59);
            this.startServiceButton.Name = "startServiceButton";
            this.startServiceButton.Size = new System.Drawing.Size(80, 29);
            this.startServiceButton.TabIndex = 7;
            this.startServiceButton.Text = "Start";
            this.startServiceButton.UseVisualStyleBackColor = true;
            this.startServiceButton.Click += new System.EventHandler(this.StartServiceButton_Click);
            this.stopServiceButton.Location = new System.Drawing.Point(101, 59);
            this.stopServiceButton.Name = "stopServiceButton";
            this.stopServiceButton.Size = new System.Drawing.Size(80, 29);
            this.stopServiceButton.TabIndex = 8;
            this.stopServiceButton.Text = "Stop";
            this.stopServiceButton.UseVisualStyleBackColor = true;
            this.stopServiceButton.Click += new System.EventHandler(this.StopServiceButton_Click);
            this.restartServiceButton.Location = new System.Drawing.Point(187, 59);
            this.restartServiceButton.Name = "restartServiceButton";
            this.restartServiceButton.Size = new System.Drawing.Size(80, 29);
            this.restartServiceButton.TabIndex = 9;
            this.restartServiceButton.Text = "Restart";
            this.restartServiceButton.UseVisualStyleBackColor = true;
            this.restartServiceButton.Click += new System.EventHandler(this.RestartServiceButton_Click);
            this.installServiceButton.Location = new System.Drawing.Point(281, 59);
            this.installServiceButton.Name = "installServiceButton";
            this.installServiceButton.Size = new System.Drawing.Size(112, 29);
            this.installServiceButton.TabIndex = 10;
            this.installServiceButton.Text = "Install service";
            this.installServiceButton.UseVisualStyleBackColor = true;
            this.installServiceButton.Click += new System.EventHandler(this.InstallServiceButton_Click);
            this.headerUninstallServiceButton.Location = new System.Drawing.Point(399, 59);
            this.headerUninstallServiceButton.Name = "headerUninstallServiceButton";
            this.headerUninstallServiceButton.Size = new System.Drawing.Size(128, 29);
            this.headerUninstallServiceButton.TabIndex = 11;
            this.headerUninstallServiceButton.Text = "Uninstall service…";
            this.headerUninstallServiceButton.UseVisualStyleBackColor = true;
            this.headerUninstallServiceButton.Click += new System.EventHandler(this.UninstallServiceButton_Click);
            // tab control
            this.mainTabControl.Controls.Add(this.routingTabPage);
            this.mainTabControl.Controls.Add(this.exclusionsTabPage);
            this.mainTabControl.Controls.Add(this.logsTabPage);
            this.mainTabControl.Controls.Add(this.settingsTabPage);
            this.mainTabControl.Dock = System.Windows.Forms.DockStyle.Fill;
            this.mainTabControl.Location = new System.Drawing.Point(0, 102);
            this.mainTabControl.Name = "mainTabControl";
            this.mainTabControl.SelectedIndex = 0;
            this.mainTabControl.Size = new System.Drawing.Size(1114, 515);
            this.mainTabControl.TabIndex = 1;
            // routing tab
            this.routingTabPage.Controls.Add(this.routingGrid);
            this.routingTabPage.Controls.Add(this.routingButtonsPanel);
            this.routingTabPage.Location = new System.Drawing.Point(4, 24);
            this.routingTabPage.Name = "routingTabPage";
            this.routingTabPage.Padding = new System.Windows.Forms.Padding(8);
            this.routingTabPage.Size = new System.Drawing.Size(1106, 487);
            this.routingTabPage.TabIndex = 0;
            this.routingTabPage.Text = "Routing";
            this.routingTabPage.UseVisualStyleBackColor = true;
            this.routingButtonsPanel.Controls.Add(this.moveDownRuleButton);
            this.routingButtonsPanel.Controls.Add(this.moveUpRuleButton);
            this.routingButtonsPanel.Controls.Add(this.removeRuleButton);
            this.routingButtonsPanel.Controls.Add(this.duplicateRuleButton);
            this.routingButtonsPanel.Controls.Add(this.editRuleButton);
            this.routingButtonsPanel.Controls.Add(this.addRuleButton);
            this.routingButtonsPanel.Dock = System.Windows.Forms.DockStyle.Top;
            this.routingButtonsPanel.Location = new System.Drawing.Point(8, 8);
            this.routingButtonsPanel.Name = "routingButtonsPanel";
            this.routingButtonsPanel.Size = new System.Drawing.Size(1090, 39);
            this.routingButtonsPanel.TabIndex = 0;
            this.addRuleButton.Location = new System.Drawing.Point(0, 3); this.addRuleButton.Name = "addRuleButton"; this.addRuleButton.Size = new System.Drawing.Size(75, 28); this.addRuleButton.TabIndex = 0; this.addRuleButton.Text = "Add"; this.addRuleButton.UseVisualStyleBackColor = true; this.addRuleButton.Click += new System.EventHandler(this.AddRuleButton_Click);
            this.editRuleButton.Location = new System.Drawing.Point(81, 3); this.editRuleButton.Name = "editRuleButton"; this.editRuleButton.Size = new System.Drawing.Size(75, 28); this.editRuleButton.TabIndex = 1; this.editRuleButton.Text = "Edit"; this.editRuleButton.UseVisualStyleBackColor = true; this.editRuleButton.Click += new System.EventHandler(this.EditRuleButton_Click);
            this.duplicateRuleButton.Location = new System.Drawing.Point(162, 3); this.duplicateRuleButton.Name = "duplicateRuleButton"; this.duplicateRuleButton.Size = new System.Drawing.Size(82, 28); this.duplicateRuleButton.TabIndex = 2; this.duplicateRuleButton.Text = "Duplicate"; this.duplicateRuleButton.UseVisualStyleBackColor = true; this.duplicateRuleButton.Click += new System.EventHandler(this.DuplicateRuleButton_Click);
            this.removeRuleButton.Location = new System.Drawing.Point(250, 3); this.removeRuleButton.Name = "removeRuleButton"; this.removeRuleButton.Size = new System.Drawing.Size(75, 28); this.removeRuleButton.TabIndex = 3; this.removeRuleButton.Text = "Remove"; this.removeRuleButton.UseVisualStyleBackColor = true; this.removeRuleButton.Click += new System.EventHandler(this.RemoveRuleButton_Click);
            this.moveUpRuleButton.Location = new System.Drawing.Point(348, 3); this.moveUpRuleButton.Name = "moveUpRuleButton"; this.moveUpRuleButton.Size = new System.Drawing.Size(80, 28); this.moveUpRuleButton.TabIndex = 4; this.moveUpRuleButton.Text = "Move up"; this.moveUpRuleButton.UseVisualStyleBackColor = true; this.moveUpRuleButton.Click += new System.EventHandler(this.MoveUpRuleButton_Click);
            this.moveDownRuleButton.Location = new System.Drawing.Point(434, 3); this.moveDownRuleButton.Name = "moveDownRuleButton"; this.moveDownRuleButton.Size = new System.Drawing.Size(92, 28); this.moveDownRuleButton.TabIndex = 5; this.moveDownRuleButton.Text = "Move down"; this.moveDownRuleButton.UseVisualStyleBackColor = true; this.moveDownRuleButton.Click += new System.EventHandler(this.MoveDownRuleButton_Click);
            this.routingGrid.AllowUserToAddRows = false;
            this.routingGrid.AllowUserToDeleteRows = false;
            this.routingGrid.AllowUserToResizeRows = false;
            this.routingGrid.AutoSizeRowsMode = System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
            this.routingGrid.BackgroundColor = System.Drawing.SystemColors.Window;
            this.routingGrid.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.routingGrid.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.orderColumn, this.applicationsColumn, this.endpointColumn, this.authenticationColumn, this.transportColumn, this.protocolsColumn, this.addressFamiliesColumn, this.warningsColumn });
            this.routingGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.routingGrid.Location = new System.Drawing.Point(8, 47);
            this.routingGrid.MultiSelect = false;
            this.routingGrid.Name = "routingGrid";
            this.routingGrid.ReadOnly = true;
            this.routingGrid.RowHeadersVisible = false;
            this.routingGrid.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.routingGrid.Size = new System.Drawing.Size(1090, 432);
            this.routingGrid.TabIndex = 1;
            this.routingGrid.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.RoutingGrid_CellDoubleClick);
            this.routingGrid.SelectionChanged += new System.EventHandler(this.RoutingGrid_SelectionChanged);
            this.routingGrid.KeyDown += new System.Windows.Forms.KeyEventHandler(this.RoutingGrid_KeyDown);
            this.orderColumn.HeaderText = "Order"; this.orderColumn.Name = "orderColumn"; this.orderColumn.ReadOnly = true; this.orderColumn.Width = 48;
            this.applicationsColumn.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill; this.applicationsColumn.FillWeight = 130F; this.applicationsColumn.HeaderText = "Applications"; this.applicationsColumn.Name = "applicationsColumn"; this.applicationsColumn.ReadOnly = true;
            this.endpointColumn.HeaderText = "Proxy endpoint"; this.endpointColumn.Name = "endpointColumn"; this.endpointColumn.ReadOnly = true; this.endpointColumn.Width = 145;
            this.authenticationColumn.HeaderText = "Authentication"; this.authenticationColumn.Name = "authenticationColumn"; this.authenticationColumn.ReadOnly = true; this.authenticationColumn.Width = 120;
            this.transportColumn.HeaderText = "Transport"; this.transportColumn.Name = "transportColumn"; this.transportColumn.ReadOnly = true; this.transportColumn.Width = 70;
            this.protocolsColumn.HeaderText = "Protocols"; this.protocolsColumn.Name = "protocolsColumn"; this.protocolsColumn.ReadOnly = true; this.protocolsColumn.Width = 110;
            this.addressFamiliesColumn.HeaderText = "Address families"; this.addressFamiliesColumn.Name = "addressFamiliesColumn"; this.addressFamiliesColumn.ReadOnly = true; this.addressFamiliesColumn.Width = 130;
            this.warningsColumn.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill; this.warningsColumn.HeaderText = "Warnings"; this.warningsColumn.Name = "warningsColumn"; this.warningsColumn.ReadOnly = true;
            // exclusions tab
            this.exclusionsTabPage.Controls.Add(this.exclusionsListBox);
            this.exclusionsTabPage.Controls.Add(this.exclusionsButtonsPanel);
            this.exclusionsTabPage.Controls.Add(this.exclusionsExplanationLabel);
            this.exclusionsTabPage.Location = new System.Drawing.Point(4, 24);
            this.exclusionsTabPage.Name = "exclusionsTabPage";
            this.exclusionsTabPage.Padding = new System.Windows.Forms.Padding(10);
            this.exclusionsTabPage.Size = new System.Drawing.Size(1106, 487);
            this.exclusionsTabPage.TabIndex = 1;
            this.exclusionsTabPage.Text = "Exclusions";
            this.exclusionsTabPage.UseVisualStyleBackColor = true;
            this.exclusionsExplanationLabel.Dock = System.Windows.Forms.DockStyle.Top;
            this.exclusionsExplanationLabel.Location = new System.Drawing.Point(10, 10);
            this.exclusionsExplanationLabel.Name = "exclusionsExplanationLabel";
            this.exclusionsExplanationLabel.Padding = new System.Windows.Forms.Padding(4);
            this.exclusionsExplanationLabel.Size = new System.Drawing.Size(1086, 67);
            this.exclusionsExplanationLabel.TabIndex = 0;
            this.exclusionsExplanationLabel.Text = "Exclusions bypass proxy routing and take priority over catch-all rules. Matching is permissive: names and path entries use substring-style matching. Exclude VPN/tunnel carrier processes when needed to prevent recursive routing.";
            this.exclusionsButtonsPanel.Controls.Add(this.addRunningExclusionButton);
            this.exclusionsButtonsPanel.Controls.Add(this.addExecutableExclusionButton);
            this.exclusionsButtonsPanel.Controls.Add(this.addPathExclusionButton);
            this.exclusionsButtonsPanel.Controls.Add(this.addManualExclusionButton);
            this.exclusionsButtonsPanel.Controls.Add(this.removeExclusionButton);
            this.exclusionsButtonsPanel.Dock = System.Windows.Forms.DockStyle.Top;
            this.exclusionsButtonsPanel.Location = new System.Drawing.Point(10, 77);
            this.exclusionsButtonsPanel.Name = "exclusionsButtonsPanel";
            this.exclusionsButtonsPanel.Size = new System.Drawing.Size(1086, 38);
            this.exclusionsButtonsPanel.TabIndex = 1;
            this.addRunningExclusionButton.AutoSize = true; this.addRunningExclusionButton.Text = "Add running process"; this.addRunningExclusionButton.UseVisualStyleBackColor = true; this.addRunningExclusionButton.Click += new System.EventHandler(this.AddRunningExclusionButton_Click);
            this.addExecutableExclusionButton.AutoSize = true; this.addExecutableExclusionButton.Text = "Add executable"; this.addExecutableExclusionButton.UseVisualStyleBackColor = true; this.addExecutableExclusionButton.Click += new System.EventHandler(this.AddExecutableExclusionButton_Click);
            this.addPathExclusionButton.AutoSize = true; this.addPathExclusionButton.Text = "Add path"; this.addPathExclusionButton.UseVisualStyleBackColor = true; this.addPathExclusionButton.Click += new System.EventHandler(this.AddPathExclusionButton_Click);
            this.addManualExclusionButton.AutoSize = true; this.addManualExclusionButton.Text = "Add manually"; this.addManualExclusionButton.UseVisualStyleBackColor = true; this.addManualExclusionButton.Click += new System.EventHandler(this.AddManualExclusionButton_Click);
            this.removeExclusionButton.AutoSize = true; this.removeExclusionButton.Text = "Remove"; this.removeExclusionButton.UseVisualStyleBackColor = true; this.removeExclusionButton.Click += new System.EventHandler(this.RemoveExclusionButton_Click);
            this.exclusionsListBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.exclusionsListBox.FormattingEnabled = true;
            this.exclusionsListBox.HorizontalScrollbar = true;
            this.exclusionsListBox.ItemHeight = 15;
            this.exclusionsListBox.Location = new System.Drawing.Point(10, 115);
            this.exclusionsListBox.Name = "exclusionsListBox";
            this.exclusionsListBox.Size = new System.Drawing.Size(1086, 362);
            this.exclusionsListBox.TabIndex = 2;
            this.exclusionsListBox.SelectedIndexChanged += new System.EventHandler(this.ExclusionsListBox_SelectedIndexChanged);
            this.exclusionsListBox.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ExclusionsListBox_KeyDown);
            // logs tab
            this.logsTabPage.Controls.Add(this.logRichTextBox);
            this.logsTabPage.Controls.Add(this.logStatusLabel);
            this.logsTabPage.Controls.Add(this.logsToolbarPanel);
            this.logsTabPage.Location = new System.Drawing.Point(4, 24);
            this.logsTabPage.Name = "logsTabPage";
            this.logsTabPage.Padding = new System.Windows.Forms.Padding(8);
            this.logsTabPage.Size = new System.Drawing.Size(1106, 487);
            this.logsTabPage.TabIndex = 2;
            this.logsTabPage.Text = "Logs";
            this.logsTabPage.UseVisualStyleBackColor = true;
            this.logsToolbarPanel.AutoSize = true;
            this.logsToolbarPanel.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.logsToolbarPanel.Controls.Add(this.followLogsCheckBox);
            this.logsToolbarPanel.Controls.Add(this.logLevelFilterLabel);
            this.logsToolbarPanel.Controls.Add(this.logLevelFilterComboBox);
            this.logsToolbarPanel.Controls.Add(this.logSearchLabel);
            this.logsToolbarPanel.Controls.Add(this.logSearchTextBox);
            this.logsToolbarPanel.Controls.Add(this.copySelectedLogButton);
            this.logsToolbarPanel.Controls.Add(this.copyVisibleLogButton);
            this.logsToolbarPanel.Controls.Add(this.clearLogViewButton);
            this.logsToolbarPanel.Controls.Add(this.openLogFileButton);
            this.logsToolbarPanel.Controls.Add(this.openLogsButton);
            this.logsToolbarPanel.Controls.Add(this.reloadLogsButton);
            this.logsToolbarPanel.Dock = System.Windows.Forms.DockStyle.Top;
            this.logsToolbarPanel.Location = new System.Drawing.Point(8, 8);
            this.logsToolbarPanel.MinimumSize = new System.Drawing.Size(0, 38);
            this.logsToolbarPanel.Name = "logsToolbarPanel";
            this.logsToolbarPanel.Size = new System.Drawing.Size(1090, 38);
            this.logsToolbarPanel.TabIndex = 0;
            this.followLogsCheckBox.AutoSize = true; this.followLogsCheckBox.Margin = new System.Windows.Forms.Padding(3, 8, 10, 3); this.followLogsCheckBox.Text = "Follow"; this.followLogsCheckBox.UseVisualStyleBackColor = true; this.followLogsCheckBox.CheckedChanged += new System.EventHandler(this.FollowLogsCheckBox_CheckedChanged);
            this.logLevelFilterLabel.AutoSize = true; this.logLevelFilterLabel.Margin = new System.Windows.Forms.Padding(3, 8, 3, 0); this.logLevelFilterLabel.Text = "&View filter (display only):";
            this.logLevelFilterComboBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList; this.logLevelFilterComboBox.Items.AddRange(new object[] { "All levels", "Error", "Warning", "Info", "Debug" }); this.logLevelFilterComboBox.Margin = new System.Windows.Forms.Padding(3, 4, 10, 3); this.logLevelFilterComboBox.Size = new System.Drawing.Size(92, 23); this.logLevelFilterComboBox.SelectedIndex = 0; this.logLevelFilterComboBox.SelectedIndexChanged += new System.EventHandler(this.LogFilterChanged);
            this.logSearchLabel.AutoSize = true; this.logSearchLabel.Margin = new System.Windows.Forms.Padding(3, 8, 3, 0); this.logSearchLabel.Text = "Search:";
            this.logSearchTextBox.Margin = new System.Windows.Forms.Padding(3, 4, 10, 3); this.logSearchTextBox.Size = new System.Drawing.Size(155, 23); this.logSearchTextBox.TextChanged += new System.EventHandler(this.LogFilterChanged);
            this.copySelectedLogButton.AutoSize = true; this.copySelectedLogButton.Text = "Copy selected"; this.copySelectedLogButton.UseVisualStyleBackColor = true; this.copySelectedLogButton.Click += new System.EventHandler(this.CopySelectedLogButton_Click);
            this.copyVisibleLogButton.AutoSize = true; this.copyVisibleLogButton.Text = "Copy visible"; this.copyVisibleLogButton.UseVisualStyleBackColor = true; this.copyVisibleLogButton.Click += new System.EventHandler(this.CopyVisibleLogButton_Click);
            this.clearLogViewButton.AutoSize = true; this.clearLogViewButton.Text = "Clear view"; this.clearLogViewButton.UseVisualStyleBackColor = true; this.clearLogViewButton.Click += new System.EventHandler(this.ClearLogViewButton_Click);
            this.openLogFileButton.AutoSize = true; this.openLogFileButton.Text = "Open log file"; this.openLogFileButton.UseVisualStyleBackColor = true; this.openLogFileButton.Click += new System.EventHandler(this.OpenLogFileButton_Click);
            this.openLogsButton.AutoSize = true; this.openLogsButton.Text = "Open log folder"; this.openLogsButton.UseVisualStyleBackColor = true; this.openLogsButton.Click += new System.EventHandler(this.OpenLogFolderButton_Click);
            this.reloadLogsButton.AutoSize = true; this.reloadLogsButton.Text = "Reload"; this.reloadLogsButton.UseVisualStyleBackColor = true; this.reloadLogsButton.Click += new System.EventHandler(this.ReloadLogsButton_Click);
            this.logStatusLabel.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.logStatusLabel.Location = new System.Drawing.Point(8, 459);
            this.logStatusLabel.Name = "logStatusLabel";
            this.logStatusLabel.Size = new System.Drawing.Size(1090, 20);
            this.logStatusLabel.TabIndex = 2;
            this.logStatusLabel.Text = "Waiting for log location…";
            this.logRichTextBox.BackColor = System.Drawing.SystemColors.Window;
            this.logRichTextBox.DetectUrls = false;
            this.logRichTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.logRichTextBox.Font = global::ProxiFyreUI.Infrastructure.WinFormsFontBootstrap.CreateUiFont("Consolas", 9F);
            this.logRichTextBox.HideSelection = false;
            this.logRichTextBox.Location = new System.Drawing.Point(8, 46);
            this.logRichTextBox.Name = "logRichTextBox";
            this.logRichTextBox.ReadOnly = true;
            this.logRichTextBox.Size = new System.Drawing.Size(1090, 413);
            this.logRichTextBox.TabIndex = 1;
            this.logRichTextBox.Text = "";
            this.logRichTextBox.WordWrap = false;
            // settings
            this.settingsTabPage.AutoScroll = true;
            this.settingsTabPage.Controls.Add(this.uninstallNoteLabel);
            this.settingsTabPage.Controls.Add(this.uninstallServiceButton);
            this.settingsTabPage.Controls.Add(this.diagnosticsGroupBox);
            this.settingsTabPage.Controls.Add(this.configurationSettingsGroupBox);
            this.settingsTabPage.Controls.Add(this.engineSettingsGroupBox);
            this.settingsTabPage.Location = new System.Drawing.Point(4, 24);
            this.settingsTabPage.Name = "settingsTabPage";
            this.settingsTabPage.Padding = new System.Windows.Forms.Padding(10);
            this.settingsTabPage.Size = new System.Drawing.Size(1106, 487);
            this.settingsTabPage.TabIndex = 3;
            this.settingsTabPage.Text = "Settings / Diagnostics";
            this.settingsTabPage.UseVisualStyleBackColor = true;
            this.engineSettingsGroupBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            this.engineSettingsGroupBox.Controls.Add(this.openLogFolderButton); this.engineSettingsGroupBox.Controls.Add(this.openConfigurationFolderButton); this.engineSettingsGroupBox.Controls.Add(this.browseEngineButton); this.engineSettingsGroupBox.Controls.Add(this.logPathTextBox); this.engineSettingsGroupBox.Controls.Add(this.logPathLabel); this.engineSettingsGroupBox.Controls.Add(this.configurationPathTextBox); this.engineSettingsGroupBox.Controls.Add(this.configurationPathLabel); this.engineSettingsGroupBox.Controls.Add(this.enginePathTextBox); this.engineSettingsGroupBox.Controls.Add(this.enginePathLabel);
            this.engineSettingsGroupBox.Location = new System.Drawing.Point(10, 10); this.engineSettingsGroupBox.Name = "engineSettingsGroupBox"; this.engineSettingsGroupBox.Size = new System.Drawing.Size(1078, 157); this.engineSettingsGroupBox.TabIndex = 0; this.engineSettingsGroupBox.TabStop = false; this.engineSettingsGroupBox.Text = "Resolved engine locations";
            this.enginePathLabel.AutoSize = true; this.enginePathLabel.Location = new System.Drawing.Point(12, 29); this.enginePathLabel.Text = "ProxiFyre executable:";
            this.enginePathTextBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right))); this.enginePathTextBox.Location = new System.Drawing.Point(151, 25); this.enginePathTextBox.ReadOnly = true; this.enginePathTextBox.Size = new System.Drawing.Size(771, 23); this.enginePathTextBox.TabIndex = 1;
            this.browseEngineButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right))); this.browseEngineButton.Location = new System.Drawing.Point(933, 23); this.browseEngineButton.Size = new System.Drawing.Size(130, 27); this.browseEngineButton.Text = "Browse for engine…"; this.browseEngineButton.UseVisualStyleBackColor = true; this.browseEngineButton.Click += new System.EventHandler(this.BrowseEngineButton_Click);
            this.configurationPathLabel.AutoSize = true; this.configurationPathLabel.Location = new System.Drawing.Point(12, 68); this.configurationPathLabel.Text = ProxiFyre.Configuration.ProxiFyrePaths.ConfigurationFileName + ":";
            this.configurationPathTextBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right))); this.configurationPathTextBox.Location = new System.Drawing.Point(151, 64); this.configurationPathTextBox.ReadOnly = true; this.configurationPathTextBox.Size = new System.Drawing.Size(771, 23); this.configurationPathTextBox.TabIndex = 3;
            this.openConfigurationFolderButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right))); this.openConfigurationFolderButton.Location = new System.Drawing.Point(933, 62); this.openConfigurationFolderButton.Size = new System.Drawing.Size(130, 27); this.openConfigurationFolderButton.Text = "Open config folder"; this.openConfigurationFolderButton.UseVisualStyleBackColor = true; this.openConfigurationFolderButton.Click += new System.EventHandler(this.OpenConfigurationFolderButton_Click);
            this.logPathLabel.AutoSize = true; this.logPathLabel.Location = new System.Drawing.Point(12, 107); this.logPathLabel.Text = "Log directory:";
            this.logPathTextBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right))); this.logPathTextBox.Location = new System.Drawing.Point(151, 103); this.logPathTextBox.ReadOnly = true; this.logPathTextBox.Size = new System.Drawing.Size(771, 23); this.logPathTextBox.TabIndex = 5;
            this.openLogFolderButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right))); this.openLogFolderButton.Location = new System.Drawing.Point(933, 101); this.openLogFolderButton.Size = new System.Drawing.Size(130, 27); this.openLogFolderButton.Text = "Open log folder"; this.openLogFolderButton.UseVisualStyleBackColor = true; this.openLogFolderButton.Click += new System.EventHandler(this.OpenLogFolderButton_Click);
            this.configurationSettingsGroupBox.Location = new System.Drawing.Point(10, 175); this.configurationSettingsGroupBox.Name = "configurationSettingsGroupBox"; this.configurationSettingsGroupBox.Size = new System.Drawing.Size(428, 175); this.configurationSettingsGroupBox.TabIndex = 1; this.configurationSettingsGroupBox.TabStop = false; this.configurationSettingsGroupBox.Text = "Engine and GUI settings";
            this.configurationSettingsGroupBox.Controls.Add(this.minimizeToTrayCheckBox); this.configurationSettingsGroupBox.Controls.Add(this.bypassLanExplanationLabel); this.configurationSettingsGroupBox.Controls.Add(this.bypassLanCheckBox); this.configurationSettingsGroupBox.Controls.Add(this.logLevelRestartNoteLabel); this.configurationSettingsGroupBox.Controls.Add(this.logLevelComboBox); this.configurationSettingsGroupBox.Controls.Add(this.logLevelLabel);
            this.logLevelLabel.AutoSize = true; this.logLevelLabel.Location = new System.Drawing.Point(13, 31); this.logLevelLabel.Text = "&Engine log level:";
            this.logLevelComboBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList; this.logLevelComboBox.Items.AddRange(new object[] { "Error", "Warning", "Info", "Debug", "All" }); this.logLevelComboBox.Location = new System.Drawing.Point(122, 27); this.logLevelComboBox.Size = new System.Drawing.Size(108, 23); this.logLevelComboBox.TabIndex = 1; this.logLevelComboBox.SelectedIndexChanged += new System.EventHandler(this.RootConfigurationControlChanged);
            this.logLevelRestartNoteLabel.AutoSize = true; this.logLevelRestartNoteLabel.ForeColor = System.Drawing.SystemColors.GrayText; this.logLevelRestartNoteLabel.Location = new System.Drawing.Point(239, 31); this.logLevelRestartNoteLabel.Text = "Takes effect after service restart.";
            this.bypassLanCheckBox.AutoSize = true; this.bypassLanCheckBox.Location = new System.Drawing.Point(16, 69); this.bypassLanCheckBox.Text = "Bypass local network (LAN) traffic"; this.bypassLanCheckBox.UseVisualStyleBackColor = true; this.bypassLanCheckBox.CheckedChanged += new System.EventHandler(this.RootConfigurationControlChanged);
            this.bypassLanExplanationLabel.ForeColor = System.Drawing.SystemColors.GrayText; this.bypassLanExplanationLabel.Location = new System.Drawing.Point(33, 92); this.bypassLanExplanationLabel.Size = new System.Drawing.Size(378, 38); this.bypassLanExplanationLabel.Text = "Allows local network traffic to remain direct while matched internet traffic uses the proxy.";
            this.minimizeToTrayCheckBox.AutoSize = true; this.minimizeToTrayCheckBox.Location = new System.Drawing.Point(16, 140); this.minimizeToTrayCheckBox.Text = "Closing the window hides ProxiFyreUI in the notification area"; this.minimizeToTrayCheckBox.UseVisualStyleBackColor = true; this.minimizeToTrayCheckBox.CheckedChanged += new System.EventHandler(this.SettingsPreferenceChanged);
            this.diagnosticsGroupBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right))); this.diagnosticsGroupBox.Location = new System.Drawing.Point(446, 175); this.diagnosticsGroupBox.Name = "diagnosticsGroupBox"; this.diagnosticsGroupBox.Size = new System.Drawing.Size(642, 175); this.diagnosticsGroupBox.TabIndex = 2; this.diagnosticsGroupBox.TabStop = false; this.diagnosticsGroupBox.Text = "Diagnostics (credentials are redacted)";
            this.diagnosticsGroupBox.Controls.Add(this.copyDiagnosticsButton); this.diagnosticsGroupBox.Controls.Add(this.architectureValueLabel); this.diagnosticsGroupBox.Controls.Add(this.architectureLabel); this.diagnosticsGroupBox.Controls.Add(this.engineVersionValueLabel); this.diagnosticsGroupBox.Controls.Add(this.engineVersionLabel); this.diagnosticsGroupBox.Controls.Add(this.guiVersionValueLabel); this.diagnosticsGroupBox.Controls.Add(this.guiVersionLabel); this.diagnosticsGroupBox.Controls.Add(this.serviceNameValueLabel); this.diagnosticsGroupBox.Controls.Add(this.serviceNameLabel);
            this.serviceNameLabel.AutoSize = true; this.serviceNameLabel.Location = new System.Drawing.Point(14, 28); this.serviceNameLabel.Text = "Service name:";
            this.serviceNameValueLabel.AutoSize = true; this.serviceNameValueLabel.Location = new System.Drawing.Point(112, 28); this.serviceNameValueLabel.Text = ProxiFyre.Configuration.ProxiFyrePaths.ServiceName;
            this.guiVersionLabel.AutoSize = true; this.guiVersionLabel.Location = new System.Drawing.Point(14, 53); this.guiVersionLabel.Text = "GUI version:";
            this.guiVersionValueLabel.AutoSize = true; this.guiVersionValueLabel.Location = new System.Drawing.Point(112, 53); this.guiVersionValueLabel.Text = "Not available";
            this.engineVersionLabel.AutoSize = true; this.engineVersionLabel.Location = new System.Drawing.Point(14, 78); this.engineVersionLabel.Text = "Engine version:";
            this.engineVersionValueLabel.AutoSize = true; this.engineVersionValueLabel.Location = new System.Drawing.Point(112, 78); this.engineVersionValueLabel.Text = "Not available";
            this.architectureLabel.AutoSize = true; this.architectureLabel.Location = new System.Drawing.Point(14, 103); this.architectureLabel.Text = "Architecture:";
            this.architectureValueLabel.AutoSize = true; this.architectureValueLabel.Location = new System.Drawing.Point(112, 103); this.architectureValueLabel.Text = "Unknown";
            this.copyDiagnosticsButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right))); this.copyDiagnosticsButton.Location = new System.Drawing.Point(473, 25); this.copyDiagnosticsButton.Size = new System.Drawing.Size(151, 29); this.copyDiagnosticsButton.Text = "Copy diagnostics"; this.copyDiagnosticsButton.UseVisualStyleBackColor = true; this.copyDiagnosticsButton.Click += new System.EventHandler(this.CopyDiagnosticsButton_Click);
            this.uninstallServiceButton.Location = new System.Drawing.Point(10, 362); this.uninstallServiceButton.Size = new System.Drawing.Size(125, 29); this.uninstallServiceButton.Text = "Uninstall service…"; this.uninstallServiceButton.UseVisualStyleBackColor = true; this.uninstallServiceButton.Click += new System.EventHandler(this.UninstallServiceButton_Click);
            this.uninstallNoteLabel.AutoSize = true; this.uninstallNoteLabel.Location = new System.Drawing.Point(145, 369); this.uninstallNoteLabel.Text = "Uninstalling preserves " + ProxiFyre.Configuration.ProxiFyrePaths.ConfigurationFileName + ", its backup, and all log files.";
            // action/status
            this.actionPanel.Controls.Add(this.operationProgressBar); this.actionPanel.Controls.Add(this.applyRestartButton); this.actionPanel.Controls.Add(this.saveButton); this.actionPanel.Controls.Add(this.validateButton); this.actionPanel.Controls.Add(this.reloadButton); this.actionPanel.Dock = System.Windows.Forms.DockStyle.Bottom; this.actionPanel.Location = new System.Drawing.Point(0, 617); this.actionPanel.Name = "actionPanel"; this.actionPanel.Size = new System.Drawing.Size(1114, 51); this.actionPanel.TabIndex = 2;
            this.reloadButton.Location = new System.Drawing.Point(12, 11); this.reloadButton.Size = new System.Drawing.Size(80, 29); this.reloadButton.Text = "Reload"; this.reloadButton.UseVisualStyleBackColor = true; this.reloadButton.Click += new System.EventHandler(this.ReloadButton_Click);
            this.validateButton.Location = new System.Drawing.Point(98, 11); this.validateButton.Size = new System.Drawing.Size(80, 29); this.validateButton.Text = "Validate"; this.validateButton.UseVisualStyleBackColor = true; this.validateButton.Click += new System.EventHandler(this.ValidateButton_Click);
            this.saveButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right))); this.saveButton.Location = new System.Drawing.Point(834, 11); this.saveButton.Size = new System.Drawing.Size(85, 29); this.saveButton.Text = "Save"; this.saveButton.UseVisualStyleBackColor = true; this.saveButton.Click += new System.EventHandler(this.SaveButton_Click);
            this.applyRestartButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right))); this.applyRestartButton.Location = new System.Drawing.Point(925, 11); this.applyRestartButton.Size = new System.Drawing.Size(173, 29); this.applyRestartButton.Text = "Apply && Restart"; this.applyRestartButton.UseVisualStyleBackColor = true; this.applyRestartButton.Click += new System.EventHandler(this.ApplyRestartButton_Click);
            this.operationProgressBar.Location = new System.Drawing.Point(197, 18); this.operationProgressBar.MarqueeAnimationSpeed = 30; this.operationProgressBar.Size = new System.Drawing.Size(130, 16); this.operationProgressBar.Style = System.Windows.Forms.ProgressBarStyle.Marquee; this.operationProgressBar.Visible = false;
            this.statusStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] { this.statusStripLabel }); this.statusStrip.Location = new System.Drawing.Point(0, 668); this.statusStrip.Name = "statusStrip"; this.statusStrip.Size = new System.Drawing.Size(1114, 22); this.statusStrip.TabIndex = 3;
            this.statusStripLabel.Spring = true; this.statusStripLabel.Text = "Ready"; this.statusStripLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // tray
            this.trayContextMenu.Items.AddRange(new System.Windows.Forms.ToolStripItem[] { this.trayOpenMenuItem, this.traySeparator1, this.trayServiceStatusMenuItem, this.trayStartMenuItem, this.trayStopMenuItem, this.trayRestartMenuItem, this.traySeparator2, this.trayOpenLogsMenuItem, this.trayExitMenuItem });
            this.trayOpenMenuItem.Font = global::ProxiFyreUI.Infrastructure.WinFormsFontBootstrap.CreateUiFont("Segoe UI", 9F, System.Drawing.FontStyle.Bold); this.trayOpenMenuItem.Text = "Open ProxiFyre"; this.trayOpenMenuItem.Click += new System.EventHandler(this.TrayOpenMenuItem_Click);
            this.trayServiceStatusMenuItem.Enabled = false; this.trayServiceStatusMenuItem.Text = "Service: Unknown";
            this.trayStartMenuItem.Text = "Start"; this.trayStartMenuItem.Click += new System.EventHandler(this.TrayStartMenuItem_Click);
            this.trayStopMenuItem.Text = "Stop"; this.trayStopMenuItem.Click += new System.EventHandler(this.TrayStopMenuItem_Click);
            this.trayRestartMenuItem.Text = "Restart"; this.trayRestartMenuItem.Click += new System.EventHandler(this.TrayRestartMenuItem_Click);
            this.trayOpenLogsMenuItem.Text = "Open logs"; this.trayOpenLogsMenuItem.Click += new System.EventHandler(this.TrayOpenLogsMenuItem_Click);
            this.trayExitMenuItem.Text = "Exit"; this.trayExitMenuItem.Click += new System.EventHandler(this.TrayExitMenuItem_Click);
            this.notifyIcon.ContextMenuStrip = this.trayContextMenu; this.notifyIcon.Text = "ProxiFyre"; this.notifyIcon.Visible = true; this.notifyIcon.DoubleClick += new System.EventHandler(this.NotifyIcon_DoubleClick);
            this.serviceRefreshTimer.Interval = 3000; this.serviceRefreshTimer.Tick += new System.EventHandler(this.ServiceRefreshTimer_Tick);
            // form
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.ClientSize = new System.Drawing.Size(1114, 690);
            this.Controls.Add(this.mainTabControl);
            this.Controls.Add(this.headerPanel);
            this.Controls.Add(this.actionPanel);
            this.Controls.Add(this.statusStrip);
            this.Font = global::ProxiFyreUI.Infrastructure.WinFormsFontBootstrap.CreateUiFont("Segoe UI", 9F);
            this.MinimumSize = new System.Drawing.Size(900, 620);
            this.Name = "MainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "ProxiFyre";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.MainForm_FormClosing);
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.MainForm_FormClosed);
            this.headerPanel.ResumeLayout(false); this.headerPanel.PerformLayout();
            this.mainTabControl.ResumeLayout(false);
            this.routingTabPage.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.routingGrid)).EndInit();
            this.routingButtonsPanel.ResumeLayout(false);
            this.exclusionsTabPage.ResumeLayout(false); this.exclusionsTabPage.PerformLayout();
            this.exclusionsButtonsPanel.ResumeLayout(false); this.exclusionsButtonsPanel.PerformLayout();
            this.logsTabPage.ResumeLayout(false);
            this.logsToolbarPanel.ResumeLayout(false); this.logsToolbarPanel.PerformLayout();
            this.settingsTabPage.ResumeLayout(false); this.settingsTabPage.PerformLayout();
            this.diagnosticsGroupBox.ResumeLayout(false); this.diagnosticsGroupBox.PerformLayout();
            this.configurationSettingsGroupBox.ResumeLayout(false); this.configurationSettingsGroupBox.PerformLayout();
            this.engineSettingsGroupBox.ResumeLayout(false); this.engineSettingsGroupBox.PerformLayout();
            this.actionPanel.ResumeLayout(false);
            this.statusStrip.ResumeLayout(false); this.statusStrip.PerformLayout();
            this.trayContextMenu.ResumeLayout(false);
            this.ResumeLayout(false); this.PerformLayout();
        }
    }
}
