namespace ProxiFyreUI.Forms
{
    partial class ProxyRuleEditorForm
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.GroupBox applicationsGroupBox;
        private System.Windows.Forms.ListBox applicationsListBox;
        private System.Windows.Forms.Button addRunningProcessButton;
        private System.Windows.Forms.Button addExecutableButton;
        private System.Windows.Forms.Button addFullPathButton;
        private System.Windows.Forms.Button addManualButton;
        private System.Windows.Forms.Button removeApplicationButton;
        private System.Windows.Forms.CheckBox catchAllCheckBox;
        private System.Windows.Forms.Label catchAllExplanationLabel;
        private System.Windows.Forms.GroupBox proxyGroupBox;
        private System.Windows.Forms.Label hostLabel;
        private System.Windows.Forms.TextBox hostTextBox;
        private System.Windows.Forms.Label portLabel;
        private System.Windows.Forms.NumericUpDown portNumeric;
        private System.Windows.Forms.Label endpointNoteLabel;
        private System.Windows.Forms.Label usernameLabel;
        private System.Windows.Forms.TextBox usernameTextBox;
        private System.Windows.Forms.Label passwordLabel;
        private System.Windows.Forms.TextBox passwordTextBox;
        private System.Windows.Forms.CheckBox showPasswordCheckBox;
        private System.Windows.Forms.GroupBox trafficGroupBox;
        private System.Windows.Forms.CheckBox tcpCheckBox;
        private System.Windows.Forms.CheckBox udpCheckBox;
        private System.Windows.Forms.CheckBox ipv4CheckBox;
        private System.Windows.Forms.CheckBox ipv6CheckBox;
        private System.Windows.Forms.Label trafficNoteLabel;
        private System.Windows.Forms.GroupBox transportGroupBox;
        private System.Windows.Forms.Label transportLabel;
        private System.Windows.Forms.ComboBox transportComboBox;
        private System.Windows.Forms.Label tlsServerNameLabel;
        private System.Windows.Forms.TextBox tlsServerNameTextBox;
        private System.Windows.Forms.Label tlsPinLabel;
        private System.Windows.Forms.TextBox tlsPinTextBox;
        private System.Windows.Forms.CheckBox allowInvalidCertificateCheckBox;
        private System.Windows.Forms.Label tlsWarningLabel;
        private System.Windows.Forms.Label validationLabel;
        private System.Windows.Forms.Button okButton;
        private System.Windows.Forms.Button cancelButton;
        private System.Windows.Forms.ErrorProvider errorProvider;

        protected override void Dispose(bool disposing)
        {
            if (disposing) components?.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.applicationsGroupBox = new System.Windows.Forms.GroupBox();
            this.catchAllExplanationLabel = new System.Windows.Forms.Label();
            this.catchAllCheckBox = new System.Windows.Forms.CheckBox();
            this.removeApplicationButton = new System.Windows.Forms.Button();
            this.addManualButton = new System.Windows.Forms.Button();
            this.addFullPathButton = new System.Windows.Forms.Button();
            this.addExecutableButton = new System.Windows.Forms.Button();
            this.addRunningProcessButton = new System.Windows.Forms.Button();
            this.applicationsListBox = new System.Windows.Forms.ListBox();
            this.proxyGroupBox = new System.Windows.Forms.GroupBox();
            this.showPasswordCheckBox = new System.Windows.Forms.CheckBox();
            this.passwordTextBox = new System.Windows.Forms.TextBox();
            this.passwordLabel = new System.Windows.Forms.Label();
            this.usernameTextBox = new System.Windows.Forms.TextBox();
            this.usernameLabel = new System.Windows.Forms.Label();
            this.endpointNoteLabel = new System.Windows.Forms.Label();
            this.portNumeric = new System.Windows.Forms.NumericUpDown();
            this.portLabel = new System.Windows.Forms.Label();
            this.hostTextBox = new System.Windows.Forms.TextBox();
            this.hostLabel = new System.Windows.Forms.Label();
            this.trafficGroupBox = new System.Windows.Forms.GroupBox();
            this.trafficNoteLabel = new System.Windows.Forms.Label();
            this.ipv6CheckBox = new System.Windows.Forms.CheckBox();
            this.ipv4CheckBox = new System.Windows.Forms.CheckBox();
            this.udpCheckBox = new System.Windows.Forms.CheckBox();
            this.tcpCheckBox = new System.Windows.Forms.CheckBox();
            this.transportGroupBox = new System.Windows.Forms.GroupBox();
            this.tlsWarningLabel = new System.Windows.Forms.Label();
            this.allowInvalidCertificateCheckBox = new System.Windows.Forms.CheckBox();
            this.tlsPinTextBox = new System.Windows.Forms.TextBox();
            this.tlsPinLabel = new System.Windows.Forms.Label();
            this.tlsServerNameTextBox = new System.Windows.Forms.TextBox();
            this.tlsServerNameLabel = new System.Windows.Forms.Label();
            this.transportComboBox = new System.Windows.Forms.ComboBox();
            this.transportLabel = new System.Windows.Forms.Label();
            this.validationLabel = new System.Windows.Forms.Label();
            this.okButton = new System.Windows.Forms.Button();
            this.cancelButton = new System.Windows.Forms.Button();
            this.errorProvider = new System.Windows.Forms.ErrorProvider(this.components);
            this.applicationsGroupBox.SuspendLayout();
            this.proxyGroupBox.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.portNumeric)).BeginInit();
            this.trafficGroupBox.SuspendLayout();
            this.transportGroupBox.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider)).BeginInit();
            this.SuspendLayout();
            this.applicationsGroupBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            this.applicationsGroupBox.Controls.Add(this.catchAllExplanationLabel);
            this.applicationsGroupBox.Controls.Add(this.catchAllCheckBox);
            this.applicationsGroupBox.Controls.Add(this.removeApplicationButton);
            this.applicationsGroupBox.Controls.Add(this.addManualButton);
            this.applicationsGroupBox.Controls.Add(this.addFullPathButton);
            this.applicationsGroupBox.Controls.Add(this.addExecutableButton);
            this.applicationsGroupBox.Controls.Add(this.addRunningProcessButton);
            this.applicationsGroupBox.Controls.Add(this.applicationsListBox);
            this.applicationsGroupBox.Location = new System.Drawing.Point(12, 10);
            this.applicationsGroupBox.Name = "applicationsGroupBox";
            this.applicationsGroupBox.Size = new System.Drawing.Size(820, 190);
            this.applicationsGroupBox.TabIndex = 0;
            this.applicationsGroupBox.TabStop = false;
            this.applicationsGroupBox.Text = "Applications (matching is ordered; first proxy rule wins)";
            this.applicationsListBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            this.applicationsListBox.FormattingEnabled = true;
            this.applicationsListBox.HorizontalScrollbar = true;
            this.applicationsListBox.ItemHeight = 15;
            this.applicationsListBox.Location = new System.Drawing.Point(12, 24);
            this.applicationsListBox.Name = "applicationsListBox";
            this.applicationsListBox.SelectionMode = System.Windows.Forms.SelectionMode.MultiExtended;
            this.applicationsListBox.Size = new System.Drawing.Size(796, 64);
            this.applicationsListBox.TabIndex = 0;
            this.applicationsListBox.SelectedIndexChanged += new System.EventHandler(this.ApplicationsListBox_SelectedIndexChanged);
            this.addRunningProcessButton.Location = new System.Drawing.Point(12, 96);
            this.addRunningProcessButton.Name = "addRunningProcessButton";
            this.addRunningProcessButton.Size = new System.Drawing.Size(132, 27);
            this.addRunningProcessButton.TabIndex = 1;
            this.addRunningProcessButton.Text = "Add running process";
            this.addRunningProcessButton.UseVisualStyleBackColor = true;
            this.addRunningProcessButton.Click += new System.EventHandler(this.AddRunningProcessButton_Click);
            this.addExecutableButton.Location = new System.Drawing.Point(150, 96);
            this.addExecutableButton.Name = "addExecutableButton";
            this.addExecutableButton.Size = new System.Drawing.Size(109, 27);
            this.addExecutableButton.TabIndex = 2;
            this.addExecutableButton.Text = "Add executable";
            this.addExecutableButton.UseVisualStyleBackColor = true;
            this.addExecutableButton.Click += new System.EventHandler(this.AddExecutableButton_Click);
            this.addFullPathButton.Location = new System.Drawing.Point(265, 96);
            this.addFullPathButton.Name = "addFullPathButton";
            this.addFullPathButton.Size = new System.Drawing.Size(94, 27);
            this.addFullPathButton.TabIndex = 3;
            this.addFullPathButton.Text = "Add full path";
            this.addFullPathButton.UseVisualStyleBackColor = true;
            this.addFullPathButton.Click += new System.EventHandler(this.AddFullPathButton_Click);
            this.addManualButton.Location = new System.Drawing.Point(365, 96);
            this.addManualButton.Name = "addManualButton";
            this.addManualButton.Size = new System.Drawing.Size(99, 27);
            this.addManualButton.TabIndex = 4;
            this.addManualButton.Text = "Add manually";
            this.addManualButton.UseVisualStyleBackColor = true;
            this.addManualButton.Click += new System.EventHandler(this.AddManualButton_Click);
            this.removeApplicationButton.Enabled = false;
            this.removeApplicationButton.Location = new System.Drawing.Point(470, 96);
            this.removeApplicationButton.Name = "removeApplicationButton";
            this.removeApplicationButton.Size = new System.Drawing.Size(80, 27);
            this.removeApplicationButton.TabIndex = 5;
            this.removeApplicationButton.Text = "Remove";
            this.removeApplicationButton.UseVisualStyleBackColor = true;
            this.removeApplicationButton.Click += new System.EventHandler(this.RemoveApplicationButton_Click);
            this.catchAllCheckBox.AutoSize = true;
            this.catchAllCheckBox.Location = new System.Drawing.Point(12, 132);
            this.catchAllCheckBox.Name = "catchAllCheckBox";
            this.catchAllCheckBox.Size = new System.Drawing.Size(340, 19);
            this.catchAllCheckBox.TabIndex = 6;
            this.catchAllCheckBox.Text = "Match all applications not handled by an earlier rule";
            this.catchAllCheckBox.UseVisualStyleBackColor = true;
            this.catchAllCheckBox.CheckedChanged += new System.EventHandler(this.CatchAllCheckBox_CheckedChanged);
            this.catchAllExplanationLabel.AutoEllipsis = true;
            this.catchAllExplanationLabel.ForeColor = System.Drawing.Color.DarkGoldenrod;
            this.catchAllExplanationLabel.Location = new System.Drawing.Point(28, 154);
            this.catchAllExplanationLabel.Name = "catchAllExplanationLabel";
            this.catchAllExplanationLabel.Size = new System.Drawing.Size(770, 30);
            this.catchAllExplanationLabel.TabIndex = 7;
            this.catchAllExplanationLabel.Text = "All unmatched applications is serialized as an explicit empty string. Place this rule last; exclusions still take priority.";
            this.proxyGroupBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            this.proxyGroupBox.Controls.Add(this.showPasswordCheckBox);
            this.proxyGroupBox.Controls.Add(this.passwordTextBox);
            this.proxyGroupBox.Controls.Add(this.passwordLabel);
            this.proxyGroupBox.Controls.Add(this.usernameTextBox);
            this.proxyGroupBox.Controls.Add(this.usernameLabel);
            this.proxyGroupBox.Controls.Add(this.endpointNoteLabel);
            this.proxyGroupBox.Controls.Add(this.portNumeric);
            this.proxyGroupBox.Controls.Add(this.portLabel);
            this.proxyGroupBox.Controls.Add(this.hostTextBox);
            this.proxyGroupBox.Controls.Add(this.hostLabel);
            this.proxyGroupBox.Location = new System.Drawing.Point(12, 206);
            this.proxyGroupBox.Name = "proxyGroupBox";
            this.proxyGroupBox.Size = new System.Drawing.Size(820, 132);
            this.proxyGroupBox.TabIndex = 1;
            this.proxyGroupBox.TabStop = false;
            this.proxyGroupBox.Text = "SOCKS5 endpoint and authentication (credentials: 255 encoded bytes each)";
            this.hostLabel.AutoSize = true;
            this.hostLabel.Location = new System.Drawing.Point(12, 27);
            this.hostLabel.Name = "hostLabel";
            this.hostLabel.Size = new System.Drawing.Size(35, 15);
            this.hostLabel.TabIndex = 0;
            this.hostLabel.Text = "Host:";
            this.hostTextBox.Location = new System.Drawing.Point(82, 23);
            this.hostTextBox.Name = "hostTextBox";
            this.hostTextBox.Size = new System.Drawing.Size(345, 23);
            this.hostTextBox.TabIndex = 1;
            this.hostTextBox.TextChanged += new System.EventHandler(this.FieldChanged);
            this.portLabel.AutoSize = true;
            this.portLabel.Location = new System.Drawing.Point(454, 27);
            this.portLabel.Name = "portLabel";
            this.portLabel.Size = new System.Drawing.Size(32, 15);
            this.portLabel.TabIndex = 2;
            this.portLabel.Text = "Port:";
            this.portNumeric.Location = new System.Drawing.Point(493, 23);
            this.portNumeric.Maximum = new decimal(new int[] { 65535, 0, 0, 0 });
            this.portNumeric.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            this.portNumeric.Name = "portNumeric";
            this.portNumeric.Size = new System.Drawing.Size(87, 23);
            this.portNumeric.TabIndex = 3;
            this.portNumeric.Value = new decimal(new int[] { 1080, 0, 0, 0 });
            this.portNumeric.ValueChanged += new System.EventHandler(this.FieldChanged);
            this.endpointNoteLabel.AutoSize = true;
            this.endpointNoteLabel.ForeColor = System.Drawing.SystemColors.GrayText;
            this.endpointNoteLabel.Location = new System.Drawing.Point(82, 51);
            this.endpointNoteLabel.Name = "endpointNoteLabel";
            this.endpointNoteLabel.Size = new System.Drawing.Size(556, 15);
            this.endpointNoteLabel.TabIndex = 4;
            this.endpointNoteLabel.Text = "IPv4 literal or hostname (A record). DNS and connectivity are not checked while editing.";
            this.usernameLabel.AutoSize = true;
            this.usernameLabel.Location = new System.Drawing.Point(12, 91);
            this.usernameLabel.Name = "usernameLabel";
            this.usernameLabel.Size = new System.Drawing.Size(63, 15);
            this.usernameLabel.TabIndex = 5;
            this.usernameLabel.Text = "Username:";
            this.usernameTextBox.Location = new System.Drawing.Point(82, 87);
            this.usernameTextBox.Name = "usernameTextBox";
            this.usernameTextBox.Size = new System.Drawing.Size(213, 23);
            this.usernameTextBox.TabIndex = 6;
            this.usernameTextBox.TextChanged += new System.EventHandler(this.FieldChanged);
            this.passwordLabel.AutoSize = true;
            this.passwordLabel.Location = new System.Drawing.Point(313, 91);
            this.passwordLabel.Name = "passwordLabel";
            this.passwordLabel.Size = new System.Drawing.Size(60, 15);
            this.passwordLabel.TabIndex = 7;
            this.passwordLabel.Text = "Password:";
            this.passwordTextBox.Location = new System.Drawing.Point(379, 87);
            this.passwordTextBox.Name = "passwordTextBox";
            this.passwordTextBox.Size = new System.Drawing.Size(207, 23);
            this.passwordTextBox.TabIndex = 8;
            this.passwordTextBox.UseSystemPasswordChar = true;
            this.passwordTextBox.TextChanged += new System.EventHandler(this.FieldChanged);
            this.showPasswordCheckBox.AutoSize = true;
            this.showPasswordCheckBox.Location = new System.Drawing.Point(604, 90);
            this.showPasswordCheckBox.Name = "showPasswordCheckBox";
            this.showPasswordCheckBox.Size = new System.Drawing.Size(105, 19);
            this.showPasswordCheckBox.TabIndex = 9;
            this.showPasswordCheckBox.Text = "Show password";
            this.showPasswordCheckBox.UseVisualStyleBackColor = true;
            this.showPasswordCheckBox.CheckedChanged += new System.EventHandler(this.ShowPasswordCheckBox_CheckedChanged);
            this.trafficGroupBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            this.trafficGroupBox.Controls.Add(this.trafficNoteLabel);
            this.trafficGroupBox.Controls.Add(this.ipv6CheckBox);
            this.trafficGroupBox.Controls.Add(this.ipv4CheckBox);
            this.trafficGroupBox.Controls.Add(this.udpCheckBox);
            this.trafficGroupBox.Controls.Add(this.tcpCheckBox);
            this.trafficGroupBox.Location = new System.Drawing.Point(12, 344);
            this.trafficGroupBox.Name = "trafficGroupBox";
            this.trafficGroupBox.Size = new System.Drawing.Size(820, 74);
            this.trafficGroupBox.TabIndex = 2;
            this.trafficGroupBox.TabStop = false;
            this.trafficGroupBox.Text = "Traffic";
            this.tcpCheckBox.AutoSize = true;
            this.tcpCheckBox.Location = new System.Drawing.Point(15, 25);
            this.tcpCheckBox.Name = "tcpCheckBox";
            this.tcpCheckBox.Size = new System.Drawing.Size(46, 19);
            this.tcpCheckBox.TabIndex = 0;
            this.tcpCheckBox.Text = "TCP";
            this.tcpCheckBox.UseVisualStyleBackColor = true;
            this.tcpCheckBox.CheckedChanged += new System.EventHandler(this.ProtocolSelectionChanged);
            this.udpCheckBox.AutoSize = true;
            this.udpCheckBox.Location = new System.Drawing.Point(79, 25);
            this.udpCheckBox.Name = "udpCheckBox";
            this.udpCheckBox.Size = new System.Drawing.Size(48, 19);
            this.udpCheckBox.TabIndex = 1;
            this.udpCheckBox.Text = "UDP";
            this.udpCheckBox.UseVisualStyleBackColor = true;
            this.udpCheckBox.CheckedChanged += new System.EventHandler(this.ProtocolSelectionChanged);
            this.ipv4CheckBox.AutoSize = true;
            this.ipv4CheckBox.Location = new System.Drawing.Point(166, 25);
            this.ipv4CheckBox.Name = "ipv4CheckBox";
            this.ipv4CheckBox.Size = new System.Drawing.Size(48, 19);
            this.ipv4CheckBox.TabIndex = 2;
            this.ipv4CheckBox.Text = "IPv4";
            this.ipv4CheckBox.UseVisualStyleBackColor = true;
            this.ipv4CheckBox.CheckedChanged += new System.EventHandler(this.AddressFamilySelectionChanged);
            this.ipv6CheckBox.AutoSize = true;
            this.ipv6CheckBox.Location = new System.Drawing.Point(232, 25);
            this.ipv6CheckBox.Name = "ipv6CheckBox";
            this.ipv6CheckBox.Size = new System.Drawing.Size(48, 19);
            this.ipv6CheckBox.TabIndex = 3;
            this.ipv6CheckBox.Text = "IPv6";
            this.ipv6CheckBox.UseVisualStyleBackColor = true;
            this.ipv6CheckBox.CheckedChanged += new System.EventHandler(this.AddressFamilySelectionChanged);
            this.trafficNoteLabel.AutoSize = true;
            this.trafficNoteLabel.ForeColor = System.Drawing.SystemColors.GrayText;
            this.trafficNoteLabel.Location = new System.Drawing.Point(313, 26);
            this.trafficNoteLabel.Name = "trafficNoteLabel";
            this.trafficNoteLabel.Size = new System.Drawing.Size(481, 15);
            this.trafficNoteLabel.TabIndex = 4;
            this.trafficNoteLabel.Text = "TLS protects the SOCKS5 control connection; it does not encrypt UDP payload datagrams.";
            this.transportGroupBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            this.transportGroupBox.Controls.Add(this.tlsWarningLabel);
            this.transportGroupBox.Controls.Add(this.allowInvalidCertificateCheckBox);
            this.transportGroupBox.Controls.Add(this.tlsPinTextBox);
            this.transportGroupBox.Controls.Add(this.tlsPinLabel);
            this.transportGroupBox.Controls.Add(this.tlsServerNameTextBox);
            this.transportGroupBox.Controls.Add(this.tlsServerNameLabel);
            this.transportGroupBox.Controls.Add(this.transportComboBox);
            this.transportGroupBox.Controls.Add(this.transportLabel);
            this.transportGroupBox.Location = new System.Drawing.Point(12, 424);
            this.transportGroupBox.Name = "transportGroupBox";
            this.transportGroupBox.Size = new System.Drawing.Size(820, 148);
            this.transportGroupBox.TabIndex = 3;
            this.transportGroupBox.TabStop = false;
            this.transportGroupBox.Text = "Upstream transport";
            this.transportLabel.AutoSize = true;
            this.transportLabel.Location = new System.Drawing.Point(12, 27);
            this.transportLabel.Name = "transportLabel";
            this.transportLabel.Size = new System.Drawing.Size(61, 15);
            this.transportLabel.TabIndex = 0;
            this.transportLabel.Text = "Transport:";
            this.transportComboBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.transportComboBox.FormattingEnabled = true;
            this.transportComboBox.Items.AddRange(new object[] { "Plain SOCKS5 over TCP", "SOCKS5 over TLS" });
            this.transportComboBox.Location = new System.Drawing.Point(124, 23);
            this.transportComboBox.Name = "transportComboBox";
            this.transportComboBox.Size = new System.Drawing.Size(237, 23);
            this.transportComboBox.TabIndex = 1;
            this.transportComboBox.SelectedIndexChanged += new System.EventHandler(this.TransportComboBox_SelectedIndexChanged);
            this.tlsServerNameLabel.AutoSize = true;
            this.tlsServerNameLabel.Location = new System.Drawing.Point(12, 61);
            this.tlsServerNameLabel.Name = "tlsServerNameLabel";
            this.tlsServerNameLabel.Size = new System.Drawing.Size(98, 15);
            this.tlsServerNameLabel.TabIndex = 2;
            this.tlsServerNameLabel.Text = "TLS server name:";
            this.tlsServerNameTextBox.Location = new System.Drawing.Point(124, 57);
            this.tlsServerNameTextBox.Name = "tlsServerNameTextBox";
            this.tlsServerNameTextBox.Size = new System.Drawing.Size(237, 23);
            this.tlsServerNameTextBox.TabIndex = 3;
            this.tlsServerNameTextBox.TextChanged += new System.EventHandler(this.FieldChanged);
            this.tlsPinLabel.AutoSize = true;
            this.tlsPinLabel.Location = new System.Drawing.Point(12, 95);
            this.tlsPinLabel.Name = "tlsPinLabel";
            this.tlsPinLabel.Size = new System.Drawing.Size(99, 15);
            this.tlsPinLabel.TabIndex = 4;
            this.tlsPinLabel.Text = "Pinned SHA-256:";
            this.tlsPinTextBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            this.tlsPinTextBox.Location = new System.Drawing.Point(124, 91);
            this.tlsPinTextBox.Name = "tlsPinTextBox";
            this.tlsPinTextBox.Size = new System.Drawing.Size(674, 23);
            this.tlsPinTextBox.TabIndex = 5;
            this.tlsPinTextBox.TextChanged += new System.EventHandler(this.FieldChanged);
            this.tlsPinTextBox.Leave += new System.EventHandler(this.TlsPinTextBox_Leave);
            this.allowInvalidCertificateCheckBox.AutoSize = true;
            this.allowInvalidCertificateCheckBox.ForeColor = System.Drawing.Color.DarkRed;
            this.allowInvalidCertificateCheckBox.Location = new System.Drawing.Point(396, 25);
            this.allowInvalidCertificateCheckBox.Name = "allowInvalidCertificateCheckBox";
            this.allowInvalidCertificateCheckBox.Size = new System.Drawing.Size(156, 19);
            this.allowInvalidCertificateCheckBox.TabIndex = 6;
            this.allowInvalidCertificateCheckBox.Text = "Allow invalid certificate";
            this.allowInvalidCertificateCheckBox.UseVisualStyleBackColor = true;
            this.allowInvalidCertificateCheckBox.CheckedChanged += new System.EventHandler(this.AllowInvalidCertificateCheckBox_CheckedChanged);
            this.tlsWarningLabel.AutoEllipsis = true;
            this.tlsWarningLabel.ForeColor = System.Drawing.Color.DarkRed;
            this.tlsWarningLabel.Location = new System.Drawing.Point(393, 50);
            this.tlsWarningLabel.Name = "tlsWarningLabel";
            this.tlsWarningLabel.Size = new System.Drawing.Size(405, 34);
            this.tlsWarningLabel.TabIndex = 7;
            this.tlsWarningLabel.Text = "Disables normal certificate validation. Prefer a pinned certificate for self-signed servers.";
            this.validationLabel.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            this.validationLabel.AutoEllipsis = true;
            this.validationLabel.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.validationLabel.Location = new System.Drawing.Point(12, 581);
            this.validationLabel.Name = "validationLabel";
            this.validationLabel.Padding = new System.Windows.Forms.Padding(6);
            this.validationLabel.Size = new System.Drawing.Size(820, 72);
            this.validationLabel.TabIndex = 4;
            this.validationLabel.Text = "Rule validation";
            this.okButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.okButton.Location = new System.Drawing.Point(676, 663);
            this.okButton.Name = "okButton";
            this.okButton.Size = new System.Drawing.Size(75, 28);
            this.okButton.TabIndex = 5;
            this.okButton.Text = "OK";
            this.okButton.UseVisualStyleBackColor = true;
            this.okButton.Click += new System.EventHandler(this.OkButton_Click);
            this.cancelButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.cancelButton.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.cancelButton.Location = new System.Drawing.Point(757, 663);
            this.cancelButton.Name = "cancelButton";
            this.cancelButton.Size = new System.Drawing.Size(75, 28);
            this.cancelButton.TabIndex = 6;
            this.cancelButton.Text = "Cancel";
            this.cancelButton.UseVisualStyleBackColor = true;
            this.errorProvider.BlinkStyle = System.Windows.Forms.ErrorBlinkStyle.NeverBlink;
            this.errorProvider.ContainerControl = this;
            this.AcceptButton = this.okButton;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this.cancelButton;
            this.ClientSize = new System.Drawing.Size(844, 703);
            this.Controls.Add(this.cancelButton);
            this.Controls.Add(this.okButton);
            this.Controls.Add(this.validationLabel);
            this.Controls.Add(this.transportGroupBox);
            this.Controls.Add(this.trafficGroupBox);
            this.Controls.Add(this.proxyGroupBox);
            this.Controls.Add(this.applicationsGroupBox);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Sizable;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.MinimumSize = new System.Drawing.Size(760, 742);
            this.Name = "ProxyRuleEditorForm";
            this.ShowInTaskbar = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Proxy rule";
            this.applicationsGroupBox.ResumeLayout(false);
            this.applicationsGroupBox.PerformLayout();
            this.proxyGroupBox.ResumeLayout(false);
            this.proxyGroupBox.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.portNumeric)).EndInit();
            this.trafficGroupBox.ResumeLayout(false);
            this.trafficGroupBox.PerformLayout();
            this.transportGroupBox.ResumeLayout(false);
            this.transportGroupBox.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider)).EndInit();
            this.ResumeLayout(false);
        }
    }
}
